version: 2
updates:
  - package-ecosystem: "uv"
    directory: "/"
    schedule:
      interval: "weekly"
    versioning-strategy: increase
    groups:
      dev-deps:
        patterns: ["ruff", "mypy", "pytest*"]
      docs-deps:
        patterns: ["mkdocs*"]
    open-pull-requests-limit: 5

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
