name: Release

on:
  push:
    tags: ["*"]

permissions:
  id-token: write
  contents: read

jobs:
  release:
    uses: damien-robotsix/robotsix-mill/.github/workflows/python-release.yml@3c5ac1dda3069742afbdd79dc326d9db4d97f17f  # main
